#!/usr/bin/env python3
"""Build lib/engine/accountLogos.ts for ALL tracked accounts from their real Salesforce
Account.Website domains (pulled via SOQL into /tmp/r1-3.txt + r4.json). Logo URL points at
Google's favicon service — a public source that loads in the corporate browser (icon.horse
and Supabase signed URLs also work; Clearbit/Google CDNs differ — Google favicon is the safe,
always-allowed one). No Supabase upload needed; the browser fetches the public URL directly."""
import json, re

# 1) account_id -> website, from the 4 SOQL batch dumps
sites = {}
for f in ("r1", "r2", "r3"):
    for line in open(f"/tmp/{f}.txt", encoding="utf-8"):
        line = line.strip()
        if not line:
            continue
        parts = line.split(None, 1)
        if len(parts) == 2:
            sites[parts[0]] = parts[1]
for o in json.load(open("/tmp/r4.json", encoding="utf-8")):
    if o.get("Website"):
        sites[o["Id"]] = o["Website"]

def to_domain(url):
    if not url:
        return None
    u = url.strip().lower()
    if u in ("0", "-", "n/a", "none", "null", "."):
        return None
    u = re.sub(r"^https?://", "", u)
    u = re.sub(r"^www\.", "", u)
    u = u.split("/")[0].split("?")[0].split("#")[0].strip().strip(".")
    if "." not in u or len(u) < 4:
        return None
    return u

accounts = json.load(open("/tmp/tracked_accounts.json", encoding="utf-8"))
logos, missing = {}, []
for a in accounts:
    dom = to_domain(sites.get(a["account_id"]))
    if dom:
        logos[a["slug"]] = f"https://www.google.com/s2/favicons?domain={dom}&sz=128"
    else:
        missing.append(a["account_name"])

with open("lib/engine/accountLogos.ts", "w", encoding="utf-8") as f:
    f.write("// AUTO-GENERATED by build_logo_map.py — account slug -> logo URL.\n")
    f.write("// Source: real Salesforce Account.Website domains -> Google favicon service\n")
    f.write("// (public, loads in-browser, no Supabase upload). Covers the full tracked book.\n")
    f.write("export const ACCOUNT_LOGOS: Record<string, string> = {\n")
    for slug in sorted(logos):
        f.write(f"  {json.dumps(slug)}: {json.dumps(logos[slug])},\n")
    f.write("};\n")

print(f"wrote {len(logos)} logos to lib/engine/accountLogos.ts")
print(f"no domain for {len(missing)}: {missing}")
