#!/usr/bin/env python3
"""Generate lib/engine/accountLogos.ts — account slug -> signed Supabase Storage logo URL.
Interim display map (the bucket is private) until the backend attaches signed URLs at read
time. Re-run after each enrichment pass to pick up new logos."""
import json, ssl, urllib.request

CTX = ssl.create_default_context(); CTX.check_hostname = False; CTX.verify_mode = ssl.CERT_NONE
env = {}
for line in open(".env.local", encoding="utf-8"):
    line = line.strip()
    if "=" in line and not line.startswith("#"):
        k, v = line.split("=", 1); env[k] = v.strip().strip('"')
SB = env["NEXT_PUBLIC_SUPABASE_URL"]; KEY = env["SUPABASE_SERVICE_ROLE_KEY"]
H = {"apikey": KEY, "Authorization": f"Bearer {KEY}", "Content-Type": "application/json"}

def post(u, body):
    r = urllib.request.Request(u, data=json.dumps(body).encode(), headers=H, method="POST")
    return json.load(urllib.request.urlopen(r, context=CTX, timeout=30))

# list every logo file
objs = []; off = 0
while True:
    d = post(f"{SB}/storage/v1/object/list/account-logos", {"prefix": "", "limit": 1000, "offset": off})
    if not d: break
    objs += d; off += len(d)
    if len(d) < 1000: break
slugs = [o["name"][:-4] for o in objs if o["name"].endswith(".png")]

ONE_YEAR = 31536000
m = {}
for sg in slugs:
    try:
        r = post(f"{SB}/storage/v1/object/sign/account-logos/{sg}.png", {"expiresIn": ONE_YEAR})
        m[sg] = f"{SB}/storage/v1{r['signedURL']}"
    except Exception as e:
        print("sign failed:", sg, e)

with open("lib/engine/accountLogos.ts", "w", encoding="utf-8") as f:
    f.write("// AUTO-GENERATED by gen_logo_map.py — account slug -> signed Supabase Storage logo URL.\n")
    f.write("// Interim display map (bucket is private); the backend will attach signed URLs at read\n")
    f.write("// time later. Re-run gen_logo_map.py after each enrichment pass to refresh.\n")
    f.write("export const ACCOUNT_LOGOS: Record<string, string> = {\n")
    for sg in sorted(m):
        f.write(f"  {json.dumps(sg)}: {json.dumps(m[sg])},\n")
    f.write("};\n")
print(f"wrote {len(m)} logos to lib/engine/accountLogos.ts")
